apiVersion: v2
name: cloudflared-ingress-operator
description: Kubernetes operator that watches for cloudflared.io/* annotations and dynamically updates cloudflared ConfigMap ingress rules
type: application
version: 0.2.0
appVersion: "0.1.0"
keywords:
  - cloudflared
  - operator
  - ingress
  - tunnel
  - cloudflare
home: https://github.com/livepeer/cloudflared-ingress-operator
sources:
  - https://github.com/livepeer/cloudflared-ingress-operator
maintainers:
  - name: Livepeer
    email: sre@livepeer.org
    url: https://livepeer.org
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Source Code
      url: https://github.com/livepeer/cloudflared-ingress-operator
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cloudflare/cloudflared
