apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cloudflare-ingress-operator.fullname" . }}-configmap
  namespace: {{ .Values.cloudflared.namespace }}
  labels:
    {{- include "cloudflare-ingress-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cloudflare-ingress-operator.fullname" . }}-configmap
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudflare-ingress-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
