{{- if .Values.watch.allNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudflare-ingress-operator.fullname" . }}-watch
  labels:
    {{- include "cloudflare-ingress-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cloudflare-ingress-operator.fullname" . }}-watch
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudflare-ingress-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
